database:
  host: http://localhost:5042
  username: user
  password: my-secret-pw

kafka:
  url: http://localhost:5555
  clientId: localApp

something: wow

number: 7000

boolean: true

array:
  value:
    - something0
    - something1
    - something2